var gulp            = require('gulp')
var babel           = require('gulp-babel')
var browserify      = require('browserify')
var babelify        = require('babelify')
var buffer          = require('vinyl-buffer')
var source          = require('vinyl-source-stream')
var path            = require('path')
var less            = require('gulp-less')
var autoprefixer    = require('gulp-autoprefixer')
var sourcemaps      = require('gulp-sourcemaps')
var minifyCSS       = require('gulp-minify-css')
var rename          = require('gulp-rename')
var concat          = require('gulp-concat')
var uglify          = require('gulp-uglify')
var connect         = require('gulp-connect')
var open            = require('gulp-open')
var data            = require('gulp-data')
var nunjucksRender  = require('gulp-nunjucks-render')
var nunjucks        = require('gulp-nunjucks-html')
var browserSync     = require('browser-sync').create()
var gulpSheets      = require('gulp-google-spreadsheets')

gulp.task('feed', function () {
    var bundler = browserify('feed.js')
    bundler.transform(babelify)

    bundler.bundle()
      .on('error', function (err) { console.error(err) })
      .pipe(source('feed.js'))
      .pipe(buffer())
      .pipe(gulp.dest('dist'))
})

gulp.task('docs', ['server'], function () {
  gulp.src(__filename)
    .pipe(open({uri: 'http://localhost:9001/docs/'}))
})

gulp.task('fetch-data', function () {
  gulpSheets('1Yz_fEijAModseWuUnaW0a4_IqNGYksNzC6qx2SwLA2k')
    .pipe(gulp.dest('./dist/assets/data'))
})
